#pragma once

#define SKILLMENU_VERSION_MAJOR 1
#define SKILLMENU_VERSION_MINOR 0
#define SKILLMENU_VERSION_PATCH 0
#define SKILLMENU_VERSION_BUILD 0

#define SKILLMENU_VERSION_STRING "1.0.0"
#define SKILLMENU_PLUGIN_NAME "SkillMenuFGFix"
#define SKILLMENU_AUTHOR "Community"
